#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="app/$APP"
CACHE_DIR="$DOKKU_ROOT/$APP/cache"
mkdir -p $CACHE_DIR
CHEF_DIR=/cache/chef
APT_DIR=/cache/apt
cat >$CACHE_DIR/chef-build <<EOF
#!/bin/bash
echo "starting"
sleep 2
mkdir -p $CHEF_DIR/cookbooks
mkdir -p $CHEF_DIR/checksum
mkdir -p $APT_DIR

#fix bug with upstart not working during install
if [[ ! -L "/sbin/initctl" ]]; then
    dpkg-divert --local --rename --add /sbin/initctl
    ln -s /bin/true /sbin/initctl
fi
if [[ -n "$APT_PROXY" ]]; then
    echo $APT_PROXY > /etc/apt/apt.conf.d/30proxy
else
    /sbin/ip route | awk '/default/ { print "Acquire::http::Proxy \"http://"\$3":8000\";" }' > /etc/apt/apt.conf.d/30proxy
fi
mkdir /chef
echo '
file_cache_path "/chef"
cookbook_path "'$CHEF_DIR'/cookbooks"
checksum_path "'$CHEF_DIR'/checksum"
' > $CHEF_DIR/solo.rb
cat $CHEF_DIR/solo.rb
echo "/app/provision /opt/chef/embedded/bin/berks install --path $CHEF_DIR/cookbooks"

cd /app/provision && /opt/chef/embedded/bin/berks install --path $CHEF_DIR/cookbooks

chef-solo -c $CHEF_DIR/solo.rb -o 'recipe[$APP::default]' --force-formatter --no-fork
pip install -r /app/requirements.txt
EOF

#echo -e "$COOKBOOK_INSTALL" > $CACHE_DIR/chef-build
chmod +x $CACHE_DIR/chef-build

echo /cache/chef-build

